name: Test GitHub Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test Commit Coach Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: '.commit-coach.yml'
