name: Test GitHub Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build action
        run: pnpm run build:action

      - name: Build CLI
        run: pnpm run build

      - name: Install CLI globally
        run: npm install -g .

      - name: Test Commit Coach Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: '.commit-coach.yml'
          comment: 'false'
          status-check: 'false'
        env:
          # Ensure the token is available as both INPUT_GITHUB_TOKEN and GITHUB_TOKEN
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
